# Generated by Django 4.1 on 2022-08-11 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityclasses',
            options={'verbose_name_plural': 'University Classes'},
        ),
    ]
